### ISSUE TITLE
Dockerfiles and Workflow migration for devstack

### ISSUE THREAD

**Issue by UsamaSadiq** [edx/public-dockerfiles#12]
## Description
- Placeholder parent issue to track progress across all services for Dockerfiles and workflow migration under the epic https://github.com/edx/edx-arch-experiments/issues/587. 

```[tasklist]
### Tasks
- [ ] https://github.com/edx/public-dockerfiles/issues/4
- [ ] https://github.com/edx/public-dockerfiles/issues/3
- [ ] https://github.com/edx/public-dockerfiles/issues/2
- [ ] https://github.com/edx/public-dockerfiles/issues/1
- [ ] https://github.com/edx/public-dockerfiles/issues/13
- [ ] https://github.com/edx/public-dockerfiles/issues/14
- [ ] https://github.com/edx/public-dockerfiles/issues/15
- [ ] https://github.com/edx/public-dockerfiles/issues/16
- [ ] https://github.com/edx/public-dockerfiles/issues/17
- [ ] https://github.com/edx/public-dockerfiles/issues/18
- [ ] https://github.com/edx/public-dockerfiles/issues/19
- [ ] https://github.com/edx/public-dockerfiles/issues/20
- [ ] https://github.com/edx/public-dockerfiles/issues/22
- [ ] https://github.com/edx/public-dockerfiles/issues/23
- [ ] https://github.com/edx/public-dockerfiles/issues/24
- [ ] https://github.com/edx/public-dockerfiles/issues/26
- [ ] https://github.com/edx/public-dockerfiles/issues/21
- [ ] https://github.com/edx/public-dockerfiles/issues/25
- [ ] https://github.com/openedx/license-manager/issues/736
```

**Comment by UsamaSadiq** [comment]
Due Date: 2024-12-14
