### ISSUE TITLE
[edx-platform] Dockerfiles and Workflow setup for Dev environment

### ISSUE THREAD

**Issue by UsamaSadiq** [edx/public-dockerfiles#3]
## Description
- Issue created under the implementation of https://github.com/edx/edx-arch-experiments/issues/587

```[tasklist]
### Tasks
- [x] Move the `Dockerfile` and `push-docker-image.yml` files present in the IDA to public-dockerfiles repository
- [x] Schedule the workflow to run once a day to build and publish dev image to [docker.io/edxops](http://docker.io/edxops) org
- [x] Add `workflow_dispatch` option to provide option to trigger the workflow manually if required
- [x] Setup email alert in case the workflow fails in building and publishing the image to notify the owning team in case of failure
- [x] Test the workflow once on pull request to verify everything is working as expected
- [x] Update the devstack references to pull the image from the updated host organization if needed
- [x] Update the GoCD pipeline code to reference Dockerfile from the updated path in `public-dockerfiles` repository
- [ ] Remove the Dockerfiles and workflow files from the source IDA repository
```

**Comment by huniafatima-arbi** [comment]
PR raised for removing dockerfile setup
Will be merged once the pipelines update
PR link: https://github.com/openedx/edx-platform/pull/35731

**Comment by huniafatima-arbi** [comment]
Removal of Dockerfile from `edx-platform` repo shall be handled by owning team.
