### ISSUE TITLE
[Course-discovery] Dockerfiles and Workflow setup for Dev environment

### ISSUE THREAD

**Issue by UsamaSadiq** [edx/public-dockerfiles#4]
## Description
- Issue created under the implementation of https://github.com/edx/edx-arch-experiments/issues/587

```[tasklist]
### Tasks
- [x] Move the `Dockerfile` and `push-docker-image.yml` files present in the IDA to public-dockerfiles repository
- [x] Schedule the workflow to run once a day to build and publish dev image to [docker.io/edxops](http://docker.io/edxops) org
- [x] Add `workflow_dispatch` option to provide option to trigger the workflow manually if required
- [x] Setup email alert in case the workflow fails in building and publishing the image to notify the owning team in case of failure
- [x] Test the workflow once on pull request to verify everything is working as expected
- [x] Update the devstack references to pull the image from the updated host organization if needed
- [ ] Update the GoCD pipeline code to reference Dockerfile from the updated path in `public-dockerfiles` repository
- [ ] Remove the Dockerfiles and workflow files from the source IDA repository
```

**Comment by mfarhan943** [comment]
I am starting to work on this issue now.

**Comment by UsamaSadiq** [comment]
Dockerfile from the upstream repo will be removed after the due date i.e. Dec 14th 2024 as per the DEPR issue.
